# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      README_CATEGORY: ${{ secrets.README_CATEGORY }}
      README_TOKEN: ${{ secrets.README_TOKEN }}
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: '14.15.4'

      - name: Build test and lint
        run: |
          npm ci
          npx eslint .
