# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build and analyze
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      README_CATEGORY: ${{ secrets.README_CATEGORY }}
      README_TOKEN: ${{ secrets.README_TOKEN }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - name: Build test and lint
        run: |
          npm ci

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

      - name: Lint
        run:
          npx eslint . --config .eslintrc.json --ext .js,.jsx,.ts,.tsx --format @microsoft/eslint-formatter-sarif --output-file eslint-results.sarif
        continue-on-error: true

      - name: Upload eslint Analysis
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true
